
###
POST http://localhost:8080/

###
GET http://localhost:8080/allUsers
###

GET http://localhost:8080/test


###
GET http://localhost:8080/userBySurname/sidorov


###
GET http://localhost:8080/usersByName/masha

###

GET http://localhost:8080/byIds/2/5

###
###
GET http://localhost:8080/usersByNameAndSurname/va/ov


###
GET http://localhost:8080/userByOneOfNames/petya/vasya


###
GET http://localhost:8080/firstNameBySurname/iv




