micronaut:
  application:
    name: micronautR2dbcReactor
flyway:
  datasources:
    default:
      enabled: true

r2dbc:
  datasources:
    default:
      schema-generate: CREATE_DROP
      dialect: MYSQL
      url: r2dbc:mysql://unit-359.labs.intellij.net:3306/micronaut?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
      username: irina
      password: jolt
